apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
    template:
      metadata:
        app: auth
      spec:
        containers:
          - name: auth
            image: mraheel83/auth:latest
            ports:
              - containerPort: 3001
            env:
              - name: PORT
                value: 3001
              # todo: JWT_SECRET should not set in template. It must be store in secret and create to container as env vars.
              - name: JWT_SECRET
                value: d8BkzH9PA0zTbGyLq65LzFiA90jQLdQLq1lVCjx6ituAwob4XWN9XOW45Mm9IkmzFmIJoR/tKRYDma3cuQDkP6obTBDSyBPqxcZXlxALpqvQGsxhvOelihLAadaAwJREjEolwMtV5a5GvZ/gZmxaLoJu9RV4iRdMxEH59XPHr262DkcOLKq08axSlYBbNhLGIbwzwZJYOIhl1d8rWeN+k5ODZhZo+3NgpOY6A==
              - name: JWT_EXPIRATION
                value: 3600
              - name: RABBIT_MQ_AUTH_QUEUE
                value: auth
