apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
    template:
      metadata:
        app: orders
      spec:
        containers:
          - name: orders
            image: mraheel83/orders:latest
            ports:
              - containerPort: 3000
            env:
              - name: PORT
                value: 3000
              - name: RABBIT_MQ_BILLING_QUEUE
                value: billing
              - name: RABBIT_MQ_AUTH_QUEUE
                value: auth
