apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: mraheel83/orders:latest
          env:
            - name: PORT
              value: '3000'
            - name: MONGODB_URI
              value: mongodb://root:password123@orders-app-mongodb-headless:27017/
            - name: RABBIT_MQ_URI
              value: amqp://user:password123@orders-app-rabbitmq:5672
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: RABBIT_MQ_BILLING_QUEUE
              value: billing